### ISSUE TITLE
ImplicitlyAnimatedList is showing the first removing item multiple times while animating a removal

### ISSUE THREAD

**Issue by agordeev** [bnxm/implicitly_animated_reorderable_list#14]
First of all, thanks for the awesome package. I'd starred and liked it 10 times if I could.

I'm having a problem with deleting multiple elements from the list. While elements are being deleted, the list renders all of them as the top removing element. Here's a screenshot:

![Simulator Screen Shot - iPhone 11 Pro - 2020-05-26 at 16 47 02](https://user-images.githubusercontent.com/2883524/82908622-e841c780-9f70-11ea-85a2-191b4e96a739.png)

Here's what I changed on `lang_page.dart`:
```dart
  @override
  void initState() {
    super.initState();
    selectedLanguages = List.generate(
        10,
        (index) => Language(
              englishName: 'Language $index',
              nativeName: 'Language $index',
            ));
    scrollController = ScrollController();
    tabController = TabController(initialIndex: 0, length: 3, vsync: this);
    Future.delayed(Duration(seconds: 4)).then((value) {
      setState(() {
        selectedLanguages = List.generate(
            2,
            (index) => Language(
                  englishName: 'Language $index',
                  nativeName: 'Language $index',
                ));
      });
    });
  }
```

**Comment by agordeev** [comment]
I found that MyersDiff returns a diff: `Deletion (Deletion index: 2, size: 8)`, so `ImplicitlyAnimatedListBase.onRemoved(int index)` gets called 8 times with the index = 8.

That's why `list.removeItem` uses the top element 8 times.

**Comment by bnxm** [comment]
Ok thanks for the report! I'll have a look at it as soon as I can.

**Comment by bnxm** [comment]
I think I fixed it. Could you check if it works now by depending on the dev branch like this:

~~~yaml
implicitly_animated_reorderable_list:
    git:
      url: https://github.com/bnxm/implicitly_animated_reorderable_list
      ref: dev
~~~
You might have to remove your old dependency, run pub get and then add the new dependency to make sure pub really uses the new version.

**Comment by agordeev** [comment]
Works good, thanks!
