### ISSUE TITLE
The list always removes the top element instead of the element I'm removing

### ISSUE THREAD

**Issue by agordeev** [bnxm/implicitly_animated_reorderable_list#15]
I'm trying to delete an element from the middle of the list, but `ImplicitlyAnimatedList` always removes the top element.

The reason is the diff algorithm returns `Modification<dynamic> index: 0, size: 10` instead of `Deletion index: 1, size: 1`. The list aren't aware of `Modification`, it only expects `Deletion` and `Insertion`. Therefore it removes the element at index 0.

A sample code:

```dart
class _Model {
  final String id;

  _Model(this.id);
}

Future<void> test1() async {
  final oldItems = List.generate(10, (index) => _Model(index.toString()));
  // If you uncomment this, everything will work as expected.
  // final newItems = List.from(oldItems);
  final newItems = List.generate(10, (index) => _Model(index.toString()));
  newItems.removeAt(1);
  final diff = await MyersDiff.diff(
    newItems,
    oldItems,
    areItemsTheSame: (oldItem, newItem) => oldItem.id == newItem.id,
    // If you set this to false, everything will work as expected.
    spawnIsolate: true,
  );
  print('old: ${oldItems.map((e) => e.id).toList()}');
  print('new: ${newItems.map((e) => e.id).toList()}');
  print('diff $diff');
}
```

This happens under these conditions:

1. You are diffing a custom class, `areItemsTheSame` is specified.
2. An isolate was spawn for calculating Myers diff.
3. `oldList` and `newList` are two different lists. Thus, we're not removing an item from `oldList` but rather recreating it without the removed item.

**Comment by bnxm** [comment]
Huh, that's weird. I can repro this and it is definitely wrong, however I am not sure yet what's causing the problem. Especially because, as you noted, it works without spawning an isolate, so I would conclude that there is nothing wrong with the algorithm itself. It might take a while until I'll find enough time to investigate this.
