### ISSUE TITLE
Occassionally looses the top item

### ISSUE THREAD

**Issue by jimmyff** [bnxm/implicitly_animated_reorderable_list#18]
Hi, firstly congrats on this plugin, it's great! I'm using this in my production app, I've experience (and had reports from users on both android & iOS) very occassionally the widget looses the top item in the list. 

This is a UI issue as the item still exists in the variable. it's just not being presented in the list. 

It's a very occassional issue so I can't reproduce it on demand. 

I've found that it usually triggers when I inject a new row (containing a 'Place here' button inbetween every row. This is how I allow my user to select a position where they want to insert the new row. The state is still fine (as this is written to firestore after placement and there is no row missing from the top, but the UI shows the list from the second item in the list not the first.

Any ideas whats happening here?

Thanks

**Comment by jimmyff** [comment]
I've just seen issue #15 -may well be the same issue?

**Comment by itssidhere** [comment]
It's happening with me too. Any updates on this?

**Comment by bnxm** [comment]
Is it possible for you guys to create some sample code that demonstrates this issue. It would be a great help to resolve this issue as I wasn't able to reproduce this yet.

**Comment by itssidhere** [comment]
It can be reproduced by StreamBuilder with a stream of Firestore collection and its builder returning an implicitly animated list. The builder of the list should generate items from the documents of the collection. Adding elements to that collection can possibly reproduce that bug. Hope it helps

**Comment by itssidhere** [comment]
@bnxm any updates on this?

**Comment by JayPerfetto** [comment]
I have the same issue with firestore lists - a normal listview.builder works fine in terms of adding new items

**Comment by jimmyff** [comment]
apologies @itssidhere i didn't respond to your question. Yes I am doing similar however although I think the fact we are all using Firestore is not part of the problem, this bug is appearing in part of my app that is not using Firestore and the widget is not using StreamBuilder.

**Comment by itssidhere** [comment]
@jimmyff  Do you have any workarounds?
