### ISSUE TITLE
Using ImplicitlyAnimatedReorderableList inside of another scrollable. 

### ISSUE THREAD

**Issue by marcglasberg** [bnxm/implicitly_animated_reorderable_list#19]
I put the `ImplicitlyAnimatedReorderableList` inside of another scrollable. 

Then I held the `Handle` and moved it. The item drags to reorder, but the parent scrollable also scrolls, which is not correct. 

Is there a recommended way of using `ImplicitlyAnimatedReorderableList` inside of another scrollable? Or this is not supported?

**Comment by marcglasberg** [comment]
Code to reproduce the problem (when you hold the handle and move it, it should not scroll the outer scrollable): 

```dart
import 'package:flutter/material.dart';
import 'package:implicitly_animated_reorderable_list/implicitly_animated_reorderable_list.dart';

void main() {
  runApp(
    MaterialApp(
      home: Material(
        child: Container(
          color: Colors.white,
          child: Demo(),
        ),
      ),
    ),
  );
}

class Demo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.yellow,
      child: SingleChildScrollView(
        child: Column(
          children: <Widget>[
            Container(height: 100, width: double.infinity, color: Colors.red),
            Container(height: 100, width: double.infinity, color: Colors.blue),
            Container(height: 100, width: double.infinity, color: Colors.green),
            Container(height: 100, width: double.infinity, color: Colors.purple),
            Container(height: 100, width: double.infinity, color: Colors.blueAccent),
            Container(height: 100, width: double.infinity, color: Colors.orangeAccent),
            Container(height: null, width: double.infinity, color: Colors.white, child: MyList()),
            Container(height: 100, width: double.infinity, color: Colors.lightBlue),
            Container(height: 100, width: double.infinity, color: Colors.deepPurpleAccent),
            Container(height: 100, width: double.infinity, color: Colors.yellowAccent),
            Container(height: 100, width: double.infinity, color: Colors.grey),
            Container(height: 100, width: double.infinity, color: Colors.pink),
            Container(height: 100, width: double.infinity, color: Colors.tealAccent),
          ],
        ),
      ),
    );
  }
}

class MyList extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ImplicitlyAnimatedReorderableList<String>(
      primary: false,
      shrinkWrap: true,
      areItemsTheSame: (String item1, String item2) => item1 == item2,
      items: const ["Item 1", "Item 2", "Item 3", "Item 4"],
      spawnIsolate: false,
      itemBuilder: _itemBuilder,
      onReorderFinished: (String item, int from, int to, List<String> newItems) {},
    );
  }
}

Reorderable _itemBuilder(
  BuildContext context,
  Animation<double> animation,
  String item,
  int index,
) {
  return Reorderable(
    key: ValueKey(item),
    builder: (context, Animation<double> dragAnimation, bool inDrag) => Row(
      children: <Widget>[
        Padding(
          padding: const EdgeInsets.all(8.0),
          child: Text(
            item,
            style: TextStyle(color: inDrag ? Colors.red : Colors.black, fontSize: 25.0),
          ),
        ),
        Handle(
          child: Container(
              height: 30,
              width: 30,
              color: Colors.grey,
              child: Icon(Icons.drag_handle, color: inDrag ? Colors.red : Colors.black)),
        ),
      ],
    ),
  );
}
```

**Comment by bnxm** [comment]
Sadly there is no way for me to disable the scrolling of a parent scrollable so you will to do this manually. When you only need to show a couple of widgets before or after the reorderable content, you could use the `header` and `footer` parameters to show a widget before and after the items respectively. 

Another option is to use the `onReorderStarted` and `onReorderFinished` callbacks and set a `NeverScrollableScrollPhysics` on the parent `Scrollable` while the item is being reordered as I have done in the [example](https://www.github.com/bnxm/implicitly_animated_reorderable_list/tree/master/example%2Flib%2Fui%2Flang_page.dart)

**Comment by marcglasberg** [comment]
Instead of disabling the parent scrolling, can't you somehow simply capture the pointer event in the handle, so that the parent scrollable doesn't receive that pointer down event?

I believe this would be the case if you used a `GestureDetector` there instead of a `Listenable` in the Handle.

**Comment by bnxm** [comment]
Due to some implementation reason I cannot simply replace the `Listener` with a `GestureDetector` but capturing the pointer event is something I will definitely try to add in the next version.

**Comment by marcglasberg** [comment]
Sure, please do. There are many use cases for a list that works inside of other lists. For example, if you want to use two ImplicitlyAnimatedReorderableList in a page. The current situation rather limits what can be achieved.

**Comment by shikhrsngh9044** [comment]
@marcglasberg   I was stuck on this issue since 5 days.. Finally found temporary solution.. Just put your ImplicitlyAnimatedReorderableList inside another ListView will solve the problem of parent scrolling..

`
class Demo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.yellow,
      child: SingleChildScrollView(
        child: Column(
          children: <Widget>[
            Container(height: 100, width: double.infinity, color: Colors.red),
            Container(
                height: 100,
                width: double.infinity,
                color: Colors.orangeAccent),
            Container(
                height: null,
                width: double.infinity,
                color: Colors.white,
                child: MyList()),
          ],
        ),
      ),
    );
  }
}

class MyList extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ListView(
      shrinkWrap: true,
      children: <Widget>[
        ImplicitlyAnimatedReorderableList<String>(
          primary: false,
          shrinkWrap: true,
          areItemsTheSame: (String item1, String item2) => item1 == item2,
          items: const ["Item 1", "Item 2", "Item 3", "Item 4"],
          spawnIsolate: false,
          itemBuilder: _itemBuilder,
          onReorderFinished:
              (String item, int from, int to, List<String> newItems) {},
        )
      ],
    );
  }
}
`

**Comment by shikhrsngh9044** [comment]
@marcglasberg Temporary solution is put your ImplicitlyAnimatedReorderableList inside another ListView will solve the problem of parent scrolling

`class Demo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.yellow,
      child: SingleChildScrollView(
        child: Column(
          children: <Widget>[
            Container(height: 100, width: double.infinity, color: Colors.red),
            Container(
                height: 100,
                width: double.infinity,
                color: Colors.orangeAccent),
            Container(
                height: null,
                width: double.infinity,
                color: Colors.white,
                child: MyList()),
          ],
        ),
      ),
    );
  }
}

class MyList extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ListView(
      shrinkWrap: true,
      children: <Widget>[
        ImplicitlyAnimatedReorderableList<String>(
          primary: false,
          shrinkWrap: true,
          areItemsTheSame: (String item1, String item2) => item1 == item2,
          items: const ["Item 1", "Item 2", "Item 3", "Item 4"],
          spawnIsolate: false,
          itemBuilder: _itemBuilder,
          onReorderFinished:
              (String item, int from, int to, List<String> newItems) {},
        )
      ],
    );
  }
}`

**Comment by AntiqPeace** [comment]
@bnxm Any update on this? As this is highly needed. 🙏 

> Another option is to use the `onReorderStarted` and `onReorderFinished` callbacks and set a `NeverScrollableScrollPhysics` on the parent `Scrollable` while the item is being reordered as I have done in the [example](https://www.github.com/bnxm/implicitly_animated_reorderable_list/tree/master/example%2Flib%2Fui%2Flang_page.dart)

This is a kind of hacky workaround. When there are many items in a reorderable list, and if we drag an item to screen edges, (imagine moving to list end), the view doesn't scroll

**Comment by innocentalone** [comment]
@bnxm sir please any updates on this? This is the most useful functionality in our projects.

**Comment by Akimenko** [comment]
+1 in waiting list.

P.S. by the way, thanks for good component

**Comment by bnxm** [comment]
I made a pre-release `(0.4.0-dev+1)` in which the `Handle` should be able to capture the pointer event and thus prevent the parent `Scrollable` from scrolling with the item. It's a bit tricky so I don't want to publish it directly to stable for now.

Note however, that the list still cannot adjust the scroll position of a parent scrollable, when the user moves an item outside of the viewport. Also note that you cannot change the parent of the `Handle` without using `Keys` as this would destroy the `State` of the `Handle`.
