### ISSUE TITLE
Grabbing the handle during the drag animation freezes the list.

### ISSUE THREAD

**Issue by marcglasberg** [bnxm/implicitly_animated_reorderable_list#21]
If you release some handle, it will start the drag animation. If you grab again the handle before this animation finishes, it will freeze the list completely. 

The workaround I'm using:

```dart
Widget _handle() => IgnorePointer(
        ignoring: !dragAnimation.isDismissed && !dragAnimation.isCompleted,
        child: Handle(
```

This seems an easy bug to fix. It should ignore the handle's `onPointerDown` if the animation is still running.

**Comment by marcglasberg** [comment]
**Update:** The above workaround makes things better but it doesn't always work. If you grab the handle right after the drag animation is finished it still freezes the list. This is a serious bug, since it really disables the widget and there is no working workaround.

**Comment by bnxm** [comment]
I pushed some commits on the dev branch that should fix this issue. Could try and see if it works now using:

~~~yaml
implicitly_animated_reorderable_list:
    git: 
      url: https://github.com/bnxm/implicitly_animated_reorderable_list
      ref: dev
~~~

I also set the `Overflow.visible` parameter and the other bug with the exception should also be fixed in that version.

**Comment by marcglasberg** [comment]
1) The freezing is fixed. 

2) The clip problem is **not** fixed: https://github.com/bnxm/implicitly_animated_reorderable_list/issues/22

3) The other bug https://github.com/bnxm/implicitly_animated_reorderable_list/issues/20 I can't reproduce, so I can't test it's fixed. I closed that issue and I'll let you know if I see that exception again.
