### ISSUE TITLE
Unnecessary clipping: The Stack should have overflow: Overflow.visible

### ISSUE THREAD

**Issue by marcglasberg** [bnxm/implicitly_animated_reorderable_list#22]
I need the Stack's `overflow` parameter to be `overflow: Overflow.visible`:

```dart
    return Stack(
      overflow: Overflow.visible,
      children: <Widget>[
        scrollView,
        if (_dragWidget != null) _buildDraggedItem(),
      ],
    );
```

Without this parameter it clips the dragged-item. This prevents the dragged item to be larger than the original one, and it also prevents you to rotate the dragged item, which is something common (for example Trello and many other apps rotate a bit the ui element while it's being dragged).

**Comment by marcglasberg** [comment]
I see that you've put the `overflow: Overflow.visible`, but the clipping is still occurring. Something else is clipping the widget, I don't know what. Are there any more `Stack`s in your code?

If you want to see the clipping it for yourself, simply rotate the widget:

```dart
return Transform(
      transform: (dragAnimation == null || dragAnimation.value == 0)
          ? Matrix4.identity()
          : (Matrix4.rotationZ(dragAnimation.value * 0.25)),
      alignment: FractionalOffset.centerRight,
      child: ......
```

**Comment by bnxm** [comment]
Isn't something like this the effect you want?


<img width="350px" src="https://user-images.githubusercontent.com/43601200/85109740-1930b780-b212-11ea-9085-5f3baed12995.gif"/>

**Comment by AlaaEldeenYsr** [comment]
Hi @bnxm , I know that this comment shouldn't be here😁, But we need you in the sliding_sheet package for some opened issues. 😃
https://github.com/bnxm/sliding-sheet/issues/43

**Comment by marcglasberg** [comment]
@bnxm Yes, exactly. So, I'm getting clipped and you are not? Weird.
