### ISSUE TITLE
Feature Request: reorder animation when order items is changed

### ISSUE THREAD

**Issue by MartinJLee** [bnxm/implicitly_animated_reorderable_list#26]
Currently, when the order of items is changed, the item in the old order will be removed and a new item will be added to the new order.
It would be nice to see if only the order of items is updated, reorder animation is triggered, instead of remove and add animations.

**Comment by bnxm** [comment]
Yeah, that would be cool however the `ListView` is based on `AnimatedList` which sadly only supports insertions and deletions yet.
