### ISSUE TITLE
Disable reorderable condition

### ISSUE THREAD

**Issue by antoine92190** [bnxm/implicitly_animated_reorderable_list#28]
Is it possible to disable the reorderable behaviour inside a ImplicitlyAnimatedReorderableList widget?
Meaning that if we try to drag an item, it would not be draggable.
This can be useful to make some specific items not reorderable, or the entire list not reorderable upon some conditions.

**Comment by antoine92190** [comment]
An easy workaround would be to set dragDuration to `Duration(days: 1)`, however `dragDuration` cannot exceed 1500ms.

**Comment by bnxm** [comment]
Well, you could add the `Handle` conditionally to the list item so that  the user wouldn't be able to reorder some specific items or none at all. I think this would give you the effect you're looking for.

**Comment by antoine92190** [comment]
Yes indeed, forgot about that as my items are fully. wrapped inside the `Handle`. Thanks!
