### ISSUE TITLE
Use with Dismissible widget

### ISSUE THREAD

**Issue by antoine92190** [bnxm/implicitly_animated_reorderable_list#31]
I would like to use the reorderable feature with the `Dismissible` flutter widget.
Note: I am wrapping the entire item inside your `Handle` widget.

However, when I slide the `Dismissible` widget, it triggers the reorderable feature which prevents `Dismissible` feature to work.

My idea is to check whether the `Dismissible` widget is being dragged, and if so, disable the `Handle` widget behaviour.
Is there a way to do that?

I guess the cleaner way to achieve this would be to add a `disable` property to the `Handle` widget.

**Comment by bentau19** [comment]
how did you combine  between the dismissible animation and the list animation
when i try to do it is delete the item ones with the dismissible animation and then it appir again and delete the object again with the list animation
do you know how to slove it?
