### ISSUE TITLE
overflow param in Stack() removed.

### ISSUE THREAD

**Issue by mikeshow** [bnxm/implicitly_animated_reorderable_list#38]
Hi,
Just to let you know, the 'overflow' param is removed in the Stack() class. Compile error then. Line 684 should be removed.

**Comment by sageata** [comment]
Yes, I face the same issue. But I guess 'fixing' this would break it for the stable version of Flutter.

**Comment by mikeshow** [comment]
Yeah I thought about that afterward, I'm in channel dev, 1.23.0-4.0.pre and I have that problem in another plugin as well. So the easiest way to fix that is for me to remove the line.

**Comment by bnxm** [comment]
I removed the overflow parameter in version 0.2.5, so I hope this will fix the issue.
