### ISSUE TITLE
Invalid value: Not in inclusive range 0..1: 2 when removing object from class

### ISSUE THREAD

**Issue by bentau19** [bnxm/implicitly_animated_reorderable_list#46]
The Code:
`List<ToDoData2> Data = [];
 @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final textTheme = theme.textTheme;

    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.amber,
      ),
      body: ImplicitlyAnimatedReorderableList<ToDoData2>(
        padding: const EdgeInsets.all(24),
        spawnIsolate: true,
        items: Data,
        areItemsTheSame: (oldItem, newItem) => oldItem == newItem,
        onReorderFinished: (item, from, to, newList) {
          setState(() {
            Data
              ..clear()
              ..addAll(newList);
          });
        },
        header: GestureDetector(
          onTap: () {
            setState(() {
              Data.add(ToDoData2(Title: "Finishing the ToDo", Context: "1) fix the animation \n 2) make saves \n 3) add lists slide bar", done: false));
            });

          },
          child: Container(
            height: 120,
            color: Colors.red,
            child: Center(
              child: Text(
                'Header',
                style: textTheme.headline6.copyWith(color: Colors.white),
              ),
            ),
          ),
        ),
        footer: Container(
          height: 120,
          color: Colors.red,
          child: Center(
            child: Text(
              'Footer',
              style: textTheme.headline6.copyWith(color: Colors.white),
            ),
          ),
        ),
        itemBuilder: (context, itemAnimation, item, index) {
          return Reorderable(
            key: ValueKey(item),
            builder: (context, dragAnimation, inDrag) {
              return SizeFadeTransition(
                  sizeFraction: 0.7,
                  animation: itemAnimation,
                    child: Card(child: Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: <Widget>[
                              IconButton(icon: Icon(Icons.add), onPressed: (){
                                setState(() {
                                  Data.removeAt(index);
                                });
                              }),
                              Text(Data[index].Title),
                              const Handle(
                                child: Icon(Icons.menu),
                              ),
                            ],
                          ),

                  )
              );;
            },
          );
        },
      ),
    );
  }

}

The class:
`class ToDoData2 {
  ToDoData2({
    this.Index,
    this.Title,
    this.Context,
    this.done,
  });

  int Index;
  String Title;
  String Context;
  bool done;}`

when I run this app and try to remove object it is makes this bug:

`he following RangeError was thrown building AnimatedBuilder(animation: AnimationController#f3472(⏮ 0.000; paused)➩_Linear, dirty, state: _AnimatedState#2c020):
RangeError (index): Invalid value: Not in inclusive range 0..1: 2

The relevant error-causing widget was: 
  Reorderable-[<Instance of 'ToDoData2'>] file:/Desktop/flutter_app/lib/ui/nested_example.dart:86:18
When the exception was thrown, this was the stack: 
#0      List.[] (dart:core-patch/growable_array.dart:177:60)
#1      VerticalNestedExampleState.build.<anonymous closure>.<anonymous closure> (package:flutter_app/ui/nested_example.dart:100:40)
#2      ReorderableState.build.buildChild (package:implicitly_animated_reorderable_list/src/reorderable.dart:123:28)
#3      ReorderableState.build.<anonymous closure> (package:implicitly_animated_reorderable_list/src/reorderable.dart:130:44)
#4      AnimatedBuilder.build (package:flutter/src/widgets/transitions.dart:1443:19)
...`

thank all who answer

**Comment by bentau19** [comment]
thanks fo all who answer but i fixed this problem

**Comment by praharshbhatt** [comment]
I'm having the same problem.
How did you fix it?

**Comment by yasinarik** [comment]
> thanks fo all who answer but i fixed this problem

hey how did you solve by the way? @bentau19

**Comment by bit-burger** [comment]
how was it fixed?

**Comment by AirborneEagle** [comment]
same here. What was the solution? @bentau19

**Comment by AirborneEagle** [comment]
I solved my issue: 
```
ImplicitlyAnimatedList<Company>(
            items: companies,
            areItemsTheSame: (a, b) => a.id == b.id,
            itemBuilder: (context, animation, company, index) =>
                SlideTransition(
              position: Tween<Offset>(
                      begin: const Offset(1, 0), end: const Offset(0, 0))
                  .animate(animation),
              child: CompanyItem(
                company: companies[index], <-------- This is the source of failure
              ),
            ),
          )
```

I was useing the changed list of compnaies, instead of the `company` object provided by the `itemBuilder` function

Solution:
```
ImplicitlyAnimatedList<Company>(
            items: companies,
            areItemsTheSame: (a, b) => a.id == b.id,
            itemBuilder: (context, animation, company, index) =>
                SlideTransition(
              position: Tween<Offset>(
                      begin: const Offset(1, 0), end: const Offset(0, 0))
                  .animate(animation),
              child: CompanyItem(
                company: company, <-------- solution
              ),
            ),
          )
```
