### ISSUE TITLE
Issue with the nested example - Dragging up with an item from bottom to top won't put the item into place

### ISSUE THREAD

**Issue by naamapps** [bnxm/implicitly_animated_reorderable_list#47]
Hey,
I appreciate all your hard work. Truly an amazing package!
I have found a bug with the given nested example - which exists in my project as well.
![SM-G955F_20201104214617](https://user-images.githubusercontent.com/37176893/98161393-57d8bd00-1ee8-11eb-9cf5-3da7e5ba6f71.gif)

As you can see from the gif, the item does not settle into the location I want, instead it goes back to the end of the list.
This bug happens only when there is a scroll in the page and I drag from the bottom upwards. no matter what position I drag it into, it won't locate itself, it will go back to its original position.
From my findings, the bug is gone when there is no scroll in the page.

Thanks again 💯

**Comment by bnxm** [comment]
Could you try with version 0.3.2 again and see if it works now?

**Comment by naamapps** [comment]
@bnxm Works like a charm! 
Thank you so much for the quick fix 👍
