### ISSUE TITLE
removeItemBuilder disables AnimatedContainer shrinkWrap animation

### ISSUE THREAD

**Issue by aytunch** [bnxm/implicitly_animated_reorderable_list#48]
My `ImplicitlyAnimatedList` is inside of a `AnimatedContainer` and the `shrinkWrap` is set to true. This way, the size of the List is determined by its items/contents. 

When `removeItemBuilder`is not null, and an item is removed from the `items`, the `AnimatedContainer` does not animate its shrinking. It shrinks instantly once the `removeDuration` finishes. When an item is added to the `items`, the `AnimatedContainer` animates perfectly.

The interesting part is that if we disable `removeItemBuilder`, then the `AnimatedContainer` can animate the shrinkage. I think there is something which causes a race condition when `removeItemBuilder` is being used.

I want to have animation and I also need the functionality of `removeItemBuilder`. I would be glad if you could help:)

```
AnimatedContainer(
   duration: const Duration(milliseconds: 500),
   child: ImplicitlyAnimatedList<int>(
      shrinkWrap: true,
      insertDuration: const Duration(milliseconds: 1200),
      updateDuration: const Duration(milliseconds: 1200),
      removeDuration: const Duration(milliseconds: 1200),
      areItemsTheSame: (a, b) => a == b,
      items: [
         0,
         1,   //<---comment this and hot reload to see shrinking
         2,
      ],
      itemBuilder: (context, animation, item, index) {
         return SizeFadeTransition(
            sizeFraction: 0.7,
            curve: Curves.easeInOut,
            animation: animation,
            child: MyWidget(),
         );
      },
      /*   //When this is commented, removing items result in AnimatedContainer to shrink with animation
      removeItemBuilder: (context, animation, oldItem) {
         return FadeTransition(
            opacity: animation,
            child: MyWidget(),
         );
      },
      */
   ),
),
```

**Comment by bnxm** [comment]
It's because you use `SizeFadeTransition` in the `itemBuilder` but only `FadeTransition` in the `removeItemBuilder`. `SizeFadeTransition` animates the size and the opacity, while `FadeTransition` only animates the opacity so you are left with an invisible widget.  This has nothing to do with the `AnimatedContainer` and you should get the same result without it. 

I hope this helps.
