### ISSUE TITLE
Reordering sometimes settles in the wrong position

### ISSUE THREAD

**Issue by cachapa** [bnxm/implicitly_animated_reorderable_list#49]
When reordering a list, the reordered item sometimes settles in the wrong position.

Steps to reproduce:
1. Start reordering an item
1. Move it to a new position
1. Move it in a different direction before the spacing animation from the previous step finishes

Because this is difficult to describe, I'm attaching a screen recording here:
I'm moving List 2 below List 4, then back up between 3 and 4.
At that moment the handler is released (notice the pointer indicator), and both List 2 and List 4 animates to the same position. List 4 then incorrectly jumps above List 2 when the animations finish.

Note that YouTube allows framestepping videos with , and .
https://www.youtube.com/watch?v=49GKbJnN-8g

**Comment by bnxm** [comment]
I revised the algorithm a bit and I think it should be better now. It's not that easy though, especially when there are multiple items moving at the same time. I made a pre-release `(0.4.0-dev+1)` along with some other changes if you want to try it out.

**Comment by cachapa** [comment]
I just tested it and couldn't reproduce it anymore. Thanks!
