### ISSUE TITLE
Allow specifying the spacing animation duration

### ISSUE THREAD

**Issue by cachapa** [bnxm/implicitly_animated_reorderable_list#50]
I find the item spacing animation while dragging an item too slow. I would like to make it snappier but couldn't find a setter for it.

On a side note, this might also mitigate (but not fix) issue #49.

**Comment by bnxm** [comment]
Actually, there is already a field for this (`dragDuration`) which determines the reorder duration and the duration of when an item settles to its final destination after a reorder, however, the fact that even I forgot about that one probably means that it is poorly named. 

I renamed it to `reorderDuration` and added two further fields: `liftDuration` which specifies the duration of the animation when a drag has been initiated and `settleDuration` which specifies the duration of the animation when an item is released after a reorder and settles to its final destination. 

I'll include them in the next release. If you want, you can depend on the dev branch and see if you can make your list more snappier now.

**Comment by cachapa** [comment]
Sorry, my bad for not noticing that field. Thanks for the notice, I've added it to my project.

I'm happy with `dragDuration` being used for both. I'll update accordingly when the next version comes out.
I was going to close this ticket bus wasn't sure if you want to use it to track that change.
