### ISSUE TITLE
Invalid value: Not in inclusive range

### ISSUE THREAD

**Issue by naamapps** [bnxm/implicitly_animated_reorderable_list#54]
I am having a problem with dynamic data when loading the list.
The data is fetched from the server and then the list will animate with the change (all good).
When scrolling the list I have a listener (I'm using this package and your other package - sliding_sheet) in the sliding sheet to know if i'm getting to the end of the list, if so I fetch more data (infinite scroll).
The problem is that the list sometime thinks there are more items in the data array for some reason.
So it throw this error:
```
E/flutter ( 1536): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/widgets/animated_list.dart': Failed assertion: line 943 pos 12: 'itemIndex >= 0 && itemIndex < _itemsCount': is not true.
E/flutter ( 1536): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter ( 1536): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter ( 1536): #2      SliverAnimatedListState.removeItem (package:flutter/src/widgets/animated_list.dart:943:12)
E/flutter ( 1536): #3      ImplicitlyAnimatedListBaseState.onRemoved (package:implicitly_animated_reorderable_list/src/implicitly_animated_list_base.dart:228:10)
E/flutter ( 1536): #4      DiffDelegate._applyDeletion (package:implicitly_animated_reorderable_list/src/diff/diff_delegate.dart:45:17)
E/flutter ( 1536): #5      DiffDelegate.applyDiffs (package:implicitly_animated_reorderable_list/src/diff/diff_delegate.dart:12:9)
E/flutter ( 1536): #6      ImplicitlyAnimatedListBaseState._calcDiffs (package:implicitly_animated_reorderable_list/src/implicitly_animated_list_base.dart:186:23)
E/flutter ( 1536): <asynchronous suspension>
E/flutter ( 1536): #7      ImplicitlyAnimatedListBaseState.didUpdateWidget (package:implicitly_animated_reorderable_list/src/implicitly_animated_list_base.dart:169:5)
```
And a bunch of this error: 
```
Another exception was thrown: RangeError (index): Invalid value: Not in inclusive range 0..9: 10
```
I really don't know what to do because I just transfer the data to the `ImplicitlyAnimatedList`. 
This error happen from time to time, It's not always happening, so I can't point you to a specific issue I found unfortunately.
Please help,
Thanks

**Comment by naamapps** [comment]
Another error that it's throwing: 
```
I/flutter ( 1536): The following RangeError was thrown building:
I/flutter ( 1536): RangeError (index): Invalid value: Valid value range is empty: 0
I/flutter ( 1536): 
I/flutter ( 1536): When the exception was thrown, this was the stack:
I/flutter ( 1536): #0      List.[] (dart:core-patch/growable_array.dart:177:60)
I/flutter ( 1536): #1      _SliverImplicitlyAnimatedListState.build.<anonymous closure> (package:implicitly_animated_reorderable_list/src/implicitly_animated_list.dart:238:26)
I/flutter ( 1536): #2      SliverAnimatedListState._itemBuilder (package:flutter/src/widgets/animated_list.dart:985:30)
```

**Comment by yasinarik** [comment]
@naamapps I think I have a similar issue. 

When removing items and adding new ones, it complains about the same error.
The state is held on a provider (with ChangeNotifier) class. All the logic happens there.

I think `onRemove`, `onRemoveComplete` and `onInsert`, `onInsertComplete` should be implemented.

**Comment by felixwortmann** [comment]
I am also getting this error, it makes the package unusable for me. <br>
My state is also held in a ChangeNotifierProvider. <br>
Every time I add an item, I get this error: 
```
flutter: The following exception was thrown building:
flutter: RangeError (index): Invalid value: Not in inclusive range 0..2: 3
flutter: 
#0      List.[] (dart:core-patch/growable_array.dart:254:60)
#1      _SliverImplicitlyAnimatedListState.build.<anonymous closure> (package:implicitly_animated_reorderable_list/src/implicitly_animated_list.dart:238:26)
#2      SliverAnimatedListState._itemBuilder (package:flutter/src/widgets/animated_list.dart:1030:30)
#3      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:455:22)
#4      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1201:28)
#5      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1214:55)
#6      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2647:19)
#7      SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1207:12)
#8      RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:349:23)
#9      RenderObject.invokeLayoutCallback.<anony<…>
```

Here is a snippet of my code:
```dart
final itemList = getProviderData()
        return ImplicitlyAnimatedList<Item>(
          items: itemList,
          areItemsTheSame: ((i1, i2) => i1.id == i2.id),
          itemBuilder: (context, animation, final Item item, _) =>
              SizeFadeTransition(
            sizeFraction: 0.7,
            curve: Curves.easeInOut,
            animation: animation,
            child: ItemWidget(item)
          ),
```

**Comment by naamapps** [comment]
I have a workaround until there will be a fix.
I found out that the cause of this issue is when there are no items at all and then you add them dynamically it throws this errors.

So I remove the list from the widget tree when there are no items, and show when there is at least one item.
It worked for me so far.

If you want it to fade in/out when showing and hiding, use an `AnimatedSwitcher`.

**Comment by zhangjun725** [comment]
> I have a workaround until there will be a fix.
> I found out that the cause of this issue is when there are no items at all and then you add them dynamically it throws this errors.
> 
> So I remove the list from the widget tree when there are no items, and show when there is at least one item.
> It worked for me so far.
> 
> If you want it to fade in/out when showing and hiding, use an `AnimatedSwitcher`.

can you share your workaround, thanks.

**Comment by itssidhere** [comment]
Any work arounds for this? It's really annoying bug

**Comment by itssidhere** [comment]
This problem is fixed in this plugin for me (https://github.com/gkpln3/automatic_animated_list) But make sure you handle the empty condition yourself as it throws error when the list gets deleted

**Comment by bnxm** [comment]
I think it should be working now in version `0.4.1`. However, hard to say without a reproduceable example.

**Comment by itssidhere** [comment]
@bnxm  Looks like it is fixed

**Comment by naamapps** [comment]
Indeed fixed.
Thanks @bnxm
