### ISSUE TITLE
[Question] Trigger/animate a reorder programatically

### ISSUE THREAD

**Issue by themadmrj** [bnxm/implicitly_animated_reorderable_list#55]
I'm not sure if this is the case, couldn't figure it out viewing the source code: it is possible to animate a reorder programatically, e.g. without the manual dragging process? For instance an external event that triggers upserting an item.

**Comment by bnxm** [comment]
Well, there won't be a reorder animation or something, but if the position of an item changes in the list, it will be animated out of its previous position and animated in to its current position. How that looks like depends on the animation you use in your `itemBuilder`.

**Comment by themadmrj** [comment]
Ye thought that much. I'm looking for a reorder animation.
