### ISSUE TITLE
Gray screen on release mode

### ISSUE THREAD

**Issue by naamapps** [bnxm/implicitly_animated_reorderable_list#57]
Hey,
I have been experiencing some exceptions when adding and removing items while in release mode.
The weird part is that in debug mode everything is fine, so I can't give you an exception message.

Hope you can have a look at this because it's really crucial for my app.
Thank

**Comment by bnxm** [comment]
Did you try out the latest pre-release and see if that works? Flutter renders a huge gray screen when there was an uncaught exception in the widget tree. Usually, this should not happen though. Are you sure that `areItemsTheSame` never returns `true` for more than one item pair? As this was the only time when I had the same issue in my apps.

**Comment by naamapps** [comment]
Hey @bnxm, thanks for replying!
I'm sure that `areItemsTheSame` is returning true for only one item pair.
I did more testing for this bug and found out that it happens when the keyboard is visible.
I'm on Android 11, galaxy note 20 ultra. Flutter 1.22.5. 
Maybe it's a flutter bug however

**Comment by shikhrsngh9044** [comment]
It happens when 
1) In the android manifest file Internet permission is not given.
2) any method is called which is returning Future in the main method. to resolve this use await.

@bnxm  @naamapps

**Comment by naamapps** [comment]
@bnxm The issue is not resolved, can you please help?
I still manage to replicate the issue:
```
I/flutter (11638): RangeError (index): Invalid value: Not in inclusive range 0..13: 14
I/flutter (11638): #0      _GrowableList.[] (dart:core-patch/growable_array.dart:254)
I/flutter (11638): #1      _SliverImplicitlyAnimatedListState.build.<anonymous closure> (package:implicitly_animated_reorderable_list/src/implicitly_animated_list.dart:235)
I/flutter (11638): #2      SliverAnimatedListState._itemBuilder (package:flutter/src/widgets/animated_list.dart:1046)
I/flutter (11638): #3      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:455)
I/flutter (11638): #4      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1213)
I/flutter (11638): #5      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1226)
```
As I mentioned it **happens only in release mode (can't replicate in debug mode)**.
My setup is like this:
Have an infinite scroll, With a search at the top (`material_floating_search_bar` - your package).
When the soft-keyboard is open and starting scrolling, I unfocus the search text field to hide the keyboard, meanwhile I still scroll the list and reach the bottom. When reaching the bottom of the list, more items are added but it seems like it adds one more item which does not exist.
Just so you know, if the keyboard is open and I don't hide it while scrolling, I can't replicate this.
**It has something to do with the keyboard hiding while scrolling and adding more items to the list simultaneously**.

See here the video:

https://user-images.githubusercontent.com/37176893/119172743-fbe21a00-ba6e-11eb-80ed-8ee8736b2d85.mp4

Please help,
Thanks
