### ISSUE TITLE
Lazy building not working ?

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [bnxm/implicitly_animated_reorderable_list#61]
Hi
Thanks for the package :)

Im logging 
```dart
itemBuilder: (context, animation, item, index) {
        print('index $index');
        if (index == comments.length - 5) {
          //bloc.fetchNextPosts();
        }
      },
```

Seems that the item builder, is called at start for all items, and then rebuild when scrolling.
Is the good behaviour, i was thinking, itembuilder is called when items are visible ?

Thank you,

**Comment by bnxm** [comment]
I cannot reproduce this with the most recent version. If this issue still persists, feel free to reopen.
