### ISSUE TITLE
null-safety/nnbd support

### ISSUE THREAD

**Issue by muhlba91** [bnxm/implicitly_animated_reorderable_list#65]
null-safety/nnbd made it into the beta channel a week ago and I wanted to ask if there's a plan to migrate the plugin to support null-safety?

**Comment by behnamsattar** [comment]
Flutter 2.0 is out and this needs to happen ASAP.

**Comment by bnxm** [comment]
0.4.0-dev+4 now has NNBD support, isn't well tested yet though.

**Comment by IchordeDionysos** [comment]
@bnxm do you feel confident now to release the null-safe version as a stable release?

**Comment by bnxm** [comment]
@IchordeDionysos Yes, I released it now as stable release.
