### ISSUE TITLE
[iOS] Exception "This widget has been unmounted..." when removing an item from a list of more than 20 - 30 items.

### ISSUE THREAD

**Issue by yixiang** [bnxm/implicitly_animated_reorderable_list#66]
════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
This widget has been unmounted, so the State no longer has a context (and should be considered defunct).

Consider canceling any active work during "dispose" or using the "mounted" getter to determine if the State is still active.
When the exception was thrown, this was the stack
#0      State.context.<anonymous closure>
package:flutter/…/widgets/framework.dart:1088
#1      State.context
package:flutter/…/widgets/framework.dart:1094
#2      ImplicitlyAnimatedReorderableListState._measureChild
package:implicitly_animated_reorderable_list/src/implicitly_animated_reorderable_list.dart:636
#3      ImplicitlyAnimatedReorderableListState.build.<anonymous closure>.<anonymous closure>
package:implicitly_animated_reorderable_list/src/implicitly_animated_reorderable_list.dart:679
#4      postFrame.<anonymous closure>
package:implicitly_animated_reorderable_list/…/util/util.dart:10
...
════════════════════════════════════════════════════════════════════════════════

**Comment by yixiang** [comment]
This issue is consistently reproducible with implicitly_animated_reorderable_list but not at all reproducible with implicitly_animated_list.

**Comment by yixiang** [comment]
it is sometimes shown as the following error:

════════ Exception caught by scheduler library ═════════════════════════════════
This widget has been unmounted, so the State no longer has a context (and should be considered defunct).
════════════════════════════════════════════════════════════════════════════════

**Comment by Albert-Jan** [comment]
Facing the same issue, any update eon how you fixed it?

**Comment by Goldy98** [comment]
Facing the same issue too ! Someone got a workaround ?

**Comment by bnxm** [comment]
Does it work if you use the version from the master branch?

~~~yaml
implicitly_animated_reorderable_list:
    git: 
      url: https://github.com/bnxm/implicitly_animated_reorderable_list
      ref: master
~~~

**Comment by Goldy98** [comment]
Let me give it a try and come back to you

**Comment by Goldy98** [comment]
@bnxm it's working with the version from the master branch
