### ISSUE TITLE
ScrollController attached to multiple scroll views (error when wrapping in a ScrollBar)

### ISSUE THREAD

**Issue by jgadsby** [bnxm/implicitly_animated_reorderable_list#67]
Hi, this is a great package and I'm enjoying using it. However, when I wrap the widget in a ScrollBar, I get this error:

`ScrollController attached to multiple scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 109 pos 12: '_positions.length == 1'
`

Here's a small code sample:

`Scrollbar(
                child: ImplicitlyAnimatedList<Object>(
                    shrinkWrap: true,
                    padding: EdgeInsets.only(bottom: 80),
                    items: items,
                    key: Key("list1"),
                    areItemsTheSame: (a, b) => a.id == b.id,
                    itemBuilder: (context, animation, item, index) {
                      return listItem(item, index, animation);
                    }))`

**Comment by bnxm** [comment]
I cannot reproduce this with the most recent version. If this issue still persists, feel free to reopen.
