### ISSUE TITLE
Items disposed

### ISSUE THREAD

**Issue by carmas123** [bnxm/implicitly_animated_reorderable_list#68]
There is a simple bug on file: `implicitly_animated_reorderable_list.dart`
At row 630 we need to add this code:

FROM:
```
  void _measureChild(Key key, [int index]) {
...

```

TO:

```
  void _measureChild(Key key, [int index]) {
    if (!mounted || !_items[key].mounted) {
      return;
    }
...
```

This check is required to bypass a debug error for disposed items.

**Comment by bnxm** [comment]
Thanks!
