### ISSUE TITLE
Only non null items

### ISSUE THREAD

**Issue by Nolence** [bnxm/implicitly_animated_reorderable_list#69]
Hi ! I don't think it's necessary to allow for null items. It seems unnecessary even considering Columns and Rows don't allow null.

If we replaced

```dart
abstract class ImplicitlyAnimatedListBase<W extends Widget, E>
    extends StatefulWidget { // ...
```

with

```dart
abstract class ImplicitlyAnimatedListBase<W extends Widget, E extends Object>
    extends StatefulWidget { // ...
```

then the `items` we provide would have to be [non-null](https://dart.dev/null-safety/understanding-null-safety#top-and-bottom) and our item diff function could instead be:

```dart
typedef ItemDiffUtil<E> = bool Function(E oldItem, E newItem);
```

**Comment by bnxm** [comment]
That's totally correct. I hadn't had the time yet to fully review what the migration tool did. Will be included in the next release or you can depend on the master branch.
