### ISSUE TITLE
ImplicitlyAnimatedReorderableListState should not dispose widget.controller

### ISSUE THREAD

**Issue by csteuer** [bnxm/implicitly_animated_reorderable_list#72]
Hi,
when a ScrollController is passed to the ImplicitlyAnimatedReorderableList it will be disposed once the widgets state is disposed.
ImplicitlyAnimatedReorderableList or rather ImplicitlyAnimatedReorderableListState should only dispose the controller if it has created it.

Greetings and thanks for the great package
Claus

**Comment by bnxm** [comment]
That is correct! It should be fixed now.
