### ISSUE TITLE
itemBuilder stops rebuilding a short time after dragging so elevation is not showing properly

### ISSUE THREAD

**Issue by naamapps** [bnxm/implicitly_animated_reorderable_list#73]
Hey,
In `itemBuilder` I have this code:
```
itemBuilder: (context, itemAnimation, item, index) {
          return Reorderable(
            key: ValueKey(item),
            builder: (context, dragAnimation, inDrag) {
              final t = dragAnimation.value;
              final elevation = lerpDouble(0, 2, t);
              return SizeFadeTransition(
                sizeFraction: 0.7,
                curve: Curves.easeInOut,
                animation: itemAnimation,
                child: Box(
                  elevation: elevation,
                  color: Theme.of(context).scaffoldBackgroundColor,
                  margin: const EdgeInsets.symmetric(vertical: 6),
```
However the elevation won't reach its max value since the `itemBuilder` stop rebuilding a short time after dragging and so the elevation stops at an early stage.
Instead of elevation to reach value of 2, it reaches 0.3.

When releasing the finger and stopping drag, the elevation jump to the max value and drops instantly.

Please help,
Thanks

**Comment by bnxm** [comment]
The `itemBuilder` does not animate its child. If you want to animate one of your child in response to a drag, you should wrap the child in an `AnimatedBuilder` and calculate the elevation in its builder.

**Comment by naamapps** [comment]
@bnxm Yes you're right!
I could have sworn that it worked before haha
Thanks for your help
