### ISSUE TITLE
Special usecases that hide last item not like original ListView.

### ISSUE THREAD

**Issue by jinfagang** [bnxm/implicitly_animated_reorderable_list#77]
this is normal ListView:

![image](https://user-images.githubusercontent.com/21303438/118293671-76a9b300-b50c-11eb-84ab-078e8890d9e1.png)

this is ChatsList (Using AnimatedReorderableList)

![image](https://user-images.githubusercontent.com/21303438/118293747-8de8a080-b50c-11eb-896a-9a8cca52295b.png)

Hi, I am not here report a bug or problem of this package. On the opposite using this lib I managed to build a useful chat App. 

But I found a slightly bias behavior might not notice by you. As you can see, when the List scroll to the bottom, ChatsList can not handle with the bottomBar, while ListView can handle,  **on the other words, ListView the last item will not blind by the navigationBar, this can be notice easily if your bottomBar blurred**.

Is there a way to replace ChatsList with ListView while also preserve all other features? I really don't know why they behavior such bias

**Comment by bnxm** [comment]
I cannot know for sure without having seen you code, but probably you haven't specified a padding to the `ImplicitlyAnimatedList`. `ListView` by default adds a `16dp` padding to itself. Adding a bottom padding of the height of the navigation bar should fix the problem.

**Comment by jinfagang** [comment]
@bnxm Thanks for your suggestion, however, this seems not a padding issue, **if add a padding, then evey item will have a padding to the bottom right? But this is not ListView behavior, ListView only have padding when it's the last item**.

Which is my problem, I simply using a ListView extended the whole screen, and I have a BottomBar, the Listview can see through behind translucent BottomBar, Normally, if listview is full screen, the last item will **blinded by bottombar right?**, But this will **not happen on ListView**, it have some way to handle it.

Do u have a thought on this?

**Comment by bnxm** [comment]
> if add a padding, then evey item will have a padding to the bottom right?

No, when using the padding field of `ImplicitlyAnimatedList` the padding is only applied to the list and not to each item, just like on a regular `ListView`.

**Comment by bnxm** [comment]
> this is right, but, in such case, the scrolling will start from padding right?

No, only if you wrap the list view inside a `Padding` widget. 

If you use `padding: EdgeInsets.only(bottom: bottomBarHeight)` on `ImplicitlyAnimatedList` it will give you the result I think your looking for.

**Comment by jinfagang** [comment]
@bnxm  thank u Sir, you might can resolve my question. Let me have a try first.
